### ISSUE TITLE
Search bar broke Lyrics plus app

### ISSUE THREAD

**Issue by FiftyFour7250** [cj123/Sensibletify#2]
Hey, it's really cool, cause I still drag mouse to the top  when I want to find something, but it broke bar in Lyrics plus app.

With

![image](https://user-images.githubusercontent.com/78786088/120396240-e73f3500-c33e-11eb-84b2-b5a651b417c9.png)

Without

![image](https://user-images.githubusercontent.com/78786088/120396317-0938b780-c33f-11eb-925c-16b16dfaeebe.png)

**Comment by cj123** [comment]
Try the latest version - I've added a new configuration option to the extension which allows you to set excluded paths for the search fix. I've included the lyrics app in the defaults.
